apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-activator-service
  labels:
    app: activator
    app.kubernetes.io/component: activator
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.activatorService.type }}
  selector:
    app: activator
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.activatorService.ports | toYaml | nindent 2 }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "kubeflow.fullname" . }}-activator-service
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - {}
  selector:
    matchLabels:
      app: activator