apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-authn-delegators
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kubeflow.fullname" . }}-authn-delegator'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-authservice'
  namespace: '{{ .Release.Namespace }}'