apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubeflow.fullname" . }}-authservice-pvc
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.authservicePvc.storageRequest | quote }}