apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-config-istio
  labels:
    app.kubernetes.io/component: net-istio
    networking.knative.dev/ingress-provider: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  _example: {{ .Values.configIstio.Example | toYaml | indent 1 }}
  gateway.kubeflow.kubeflow-gateway: {{ .Values.configIstio.gatewayKubeflowKubeflowGateway
    | quote }}