apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-config-ping-defaults
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.10.1
    knative.dev/example-checksum: 9185c153
data:
  _example: {{ .Values.configPingDefaults.Example | toYaml | indent 1 }}