apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-config-tracing
  labels:
    app.kubernetes.io/component: knative-eventing
    knative.dev/config-category: eventing
    knative.dev/config-propagation: original
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: 0492ceb0
data:
  _example: {{ .Values.configTracing.Example | toYaml | indent 1 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-config-tracing
  labels:
    app.kubernetes.io/component: tracing
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: "26614636"
data:
  _example: {{ .Values.configTracing.Example | toYaml | indent 1 }}