apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-config-observability
  labels:
    app.kubernetes.io/component: knative-eventing
    knative.dev/config-category: eventing
    knative.dev/config-propagation: original
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: f46cf09d
data:
  _example: {{ .Values.configObservability.Example | toYaml | indent 1 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-config-observability
  labels:
    app.kubernetes.io/component: observability
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: fed4756e
data:
  _example: {{ .Values.configObservability.Example | toYaml | indent 1 }}