apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-config-domain
  labels:
    app.kubernetes.io/component: controller
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: 26c09de5
data:
  _example: {{ .Values.configDomain.Example | toYaml | indent 1 }}