apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeflow.fullname" . }}-eventing-webhook-certs
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}