apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-eventing-webhook
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
    role: eventing-webhook
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.eventingWebhook.type }}
  selector:
    app.kubernetes.io/component: knative-eventing
    app.kubernetes.io/name: knative-eventing
    kustomize.component: knative
    role: eventing-webhook
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.eventingWebhook.ports | toYaml | nindent 2 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kubeflow.fullname" . }}-eventing-webhook
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.eventingWebhook.minAvailable }}
  maxUnavailable: {{ .Values.eventingWebhook.maxUnavailable }}
  selector:
    matchLabels:
      app: eventing-webhook
      app.kubernetes.io/component: knative-eventing
      app.kubernetes.io/name: knative-eventing
      kustomize.component: knative
    {{- include "kubeflow.selectorLabels" . | nindent 6 }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kubeflow.fullname" . }}-eventing-webhook
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 100
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eventing-webhook