apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-istiod
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: unknown
    istio: pilot
    istio.io/rev: default
    operator.istio.io/component: Pilot
    release: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.istiod.type }}
  selector:
    app: istiod
    istio: pilot
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.istiod.ports | toYaml | nindent 2 }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kubeflow.fullname" . }}-istiod
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    operator.istio.io/component: Pilot
    release: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istiod