apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-jupyter-web-app-jupyter-notebook-role-binding
  labels:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "kubeflow.fullname" . }}-jupyter-web-app-jupyter-notebook-role'
subjects:
- kind: ServiceAccount
  name: jupyter-notebook
  namespace: '{{ .Release.Namespace }}'