apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-katib-mysql
  labels:
    katib.kubeflow.org/component: mysql
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.katibMysql.type }}
  selector:
    katib.kubeflow.org/component: mysql
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.katibMysql.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubeflow.fullname" . }}-katib-mysql
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.katibMysql.storageRequest | quote }}