apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeflow.fullname" . }}-katib-mysql-secrets
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  MYSQL_ROOT_PASSWORD: {{ required "katibMysqlSecrets.mysqlRootPassword is required"
    .Values.katibMysqlSecrets.mysqlRootPassword | b64enc | quote }}
type: Opaque