apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-katib-controller
  labels:
    katib.kubeflow.org/component: controller
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.katibController.type }}
  selector:
    katib.kubeflow.org/component: controller
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.katibController.ports | toYaml | nindent 2 }}