apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kubeflow.fullname" . }}-kfp-cache-cert
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  commonName: kfp-cache-cert
  dnsNames:
  - '{{ include "kubeflow.fullname" . }}-cache-server'
  - '{{ include "kubeflow.fullname" . }}-cache-server.kubeflow'
  - '{{ include "kubeflow.fullname" . }}-cache-server.kubeflow.svc'
  isCA: true
  issuerRef:
    kind: Issuer
    name: '{{ include "kubeflow.fullname" . }}-kfp-cache-selfsigned-issuer'
  secretName: webhook-server-tls