apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-kfp-launcher
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  defaultPipelineRoot: {{ .Values.kfpLauncher.defaultPipelineRoot | quote }}