apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-kserve-proxy-role
  labels:
    app: kserve
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-kserve-proxy-rolebinding
  labels:
    app: kserve
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kubeflow.fullname" . }}-kserve-proxy-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-kserve-controller-manager'
  namespace: '{{ .Release.Namespace }}'