apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-kserve-controller-manager-service
  labels:
    app: kserve
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: "1.0"
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kserveControllerManagerService.type }}
  selector:
    app: kserve
    app.kubernetes.io/name: kserve
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: "1.0"
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.kserveControllerManagerService.ports | toYaml | nindent 2 }}