apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-net-istio-webhook
  labels:
    app.kubernetes.io/component: net-istio
    networking.knative.dev/ingress-provider: istio
    role: net-istio-webhook
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.netIstioWebhook.type }}
  selector:
    app: net-istio-webhook
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.netIstioWebhook.ports | toYaml | nindent 2 }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "kubeflow.fullname" . }}-net-istio-webhook
  labels:
    app.kubernetes.io/component: net-istio
    networking.knative.dev/ingress-provider: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  portLevelMtls:
    "8443":
      mode: PERMISSIVE
  selector:
    matchLabels:
      app: net-istio-webhook