apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-notebook-controller-service
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.notebookControllerService.type }}
  selector:
    app: notebook-controller
    kustomize.component: notebook-controller
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.notebookControllerService.ports | toYaml | nindent 2 }}