apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubeflow.fullname" . }}-pvcviewer-leader-election-role
  labels:
    app: pvcviewer
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/part-of: pvc-viewer
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-pvcviewer-leader-election-rolebinding
  labels:
    app: pvcviewer
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/part-of: pvc-viewer
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "kubeflow.fullname" . }}-pvcviewer-leader-election-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-pvcviewer-controller-manager'
  namespace: '{{ .Release.Namespace }}'