apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-pvcviewer-proxy-role
  labels:
    app: pvcviewer
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/part-of: pvc-viewer
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-pvcviewer-proxy-rolebinding
  labels:
    app: pvcviewer
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/part-of: pvc-viewer
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kubeflow.fullname" . }}-pvcviewer-proxy-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-pvcviewer-controller-manager'
  namespace: '{{ .Release.Namespace }}'