apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubeflow.fullname" . }}-pvcviewer-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kubeflow.fullname" . }}-kubeflow/pvcviewer-serving-cert
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "kubeflow.fullname" . }}-pvcviewer-webhook-service'
      namespace: kubeflow
      path: /validate-kubeflow-org-v1alpha1-pvcviewer
  failurePolicy: Fail
  name: vpvcviewer.kb.io
  rules:
  - apiGroups:
    - kubeflow.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pvcviewers
  sideEffects: None