apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "kubeflow.fullname" . }}-service-cache-server
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  rules:
  - {}
  selector:
    matchLabels:
      app: cache-server