apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-dex
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.dex.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-cert-manager
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.certManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-cert-manager-cainjector
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.certManagerCainjector.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-cert-manager-webhook
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.certManagerWebhook.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-authservice
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.authservice.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-cluster-local-gateway-service-account
  labels:
    app: cluster-local-gateway
    install.operator.istio.io/owning-resource: unknown
    istio: cluster-local-gateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.clusterLocalGatewayServiceAccount.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-istio-ingressgateway-service-account
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.istioIngressgatewayServiceAccount.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-istio-reader-service-account
  labels:
    app: istio-reader
    release: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.istioReaderServiceAccount.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-istiod
  labels:
    app: istiod
    release: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.istiod.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-istiod-service-account
  labels:
    app: istiod
    release: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.istiodServiceAccount.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-eventing-controller
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.eventingController.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-eventing-webhook
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.eventingWebhook.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-pingsource-mt-adapter
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.pingsourceMtAdapter.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-controller
  labels:
    app.kubernetes.io/component: controller
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controller.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-admission-webhook-service-account
  labels:
    app: poddefaults
    app.kubernetes.io/component: poddefaults
    kustomize.component: poddefaults
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.admissionWebhookServiceAccount.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-argo
  labels:
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.argo.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-centraldashboard
  labels:
    app: centraldashboard
    app.kubernetes.io/component: centraldashboard
    kustomize.component: centraldashboard
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.centraldashboard.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-jupyter-web-app-service-account
  labels:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.jupyterWebAppServiceAccount.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-katib-controller
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.katibController.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-katib-ui
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.katibUi.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-kserve-controller-manager
  labels:
    app: kserve
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.kserveControllerManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-kserve-models-web-app
  labels:
    app: kserve
    app.kubernetes.io/component: kserve-models-web-app
    kustomize.component: kserve-models-web-app
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.kserveModelsWebApp.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-kubeflow-pipelines-cache
  labels:
    app: cache-server
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.kubeflowPipelinesCache.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-kubeflow-pipelines-container-builder
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.kubeflowPipelinesContainerBuilder.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-kubeflow-pipelines-metadata-writer
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.kubeflowPipelinesMetadataWriter.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-kubeflow-pipelines-viewer
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.kubeflowPipelinesViewer.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-meta-controller-service
  labels:
    application-crd-id: kubeflow-pipelines
    kustomize.component: metacontroller
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.metaControllerService.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-metadata-grpc-server
  labels:
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.metadataGrpcServer.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.mlPipeline.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline-persistenceagent
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.mlPipelinePersistenceagent.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline-scheduledworkflow
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.mlPipelineScheduledworkflow.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline-ui
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.mlPipelineUi.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline-viewer-crd-service-account
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.mlPipelineViewerCrdServiceAccount.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline-visualizationserver
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.mlPipelineVisualizationserver.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-mysql
  labels:
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.mysql.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-notebook-controller-service-account
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.notebookControllerServiceAccount.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-pipeline-runner
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.pipelineRunner.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-profiles-controller-service-account
  labels:
    kustomize.component: profiles
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.profilesControllerServiceAccount.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-pvcviewer-controller-manager
  labels:
    app: pvcviewer
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/part-of: pvc-viewer
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.pvcviewerControllerManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-tensorboard-controller-controller-manager
  labels:
    app: tensorboard-controller
    kustomize.component: tensorboard-controller
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.tensorboardControllerControllerManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-tensorboards-web-app-service-account
  labels:
    app: tensorboards-web-app
    kustomize.component: tensorboards-web-app
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.tensorboardsWebAppServiceAccount.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-training-operator
  labels:
    app: training-operator
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.trainingOperator.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.fullname" . }}-volumes-web-app-service-account
  labels:
    app: volumes-web-app
    kustomize.component: volumes-web-app
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.volumesWebAppServiceAccount.serviceAccount.annotations | nindent 4 }}