apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-serving-addressable-resolver
  labels:
    app.kubernetes.io/component: knative-eventing
    duck.knative.dev/addressable: "true"
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - serving.knative.dev
  resources:
  - routes
  - routes/status
  - services
  - services/status
  verbs:
  - get
  - list
  - watch