apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-admission-webhook-service
  labels:
    app: poddefaults
    app.kubernetes.io/component: poddefaults
    kustomize.component: poddefaults
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admissionWebhookService.type }}
  selector:
    app: poddefaults
    app.kubernetes.io/component: poddefaults
    app.kubernetes.io/name: poddefaults
    kustomize.component: poddefaults
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.admissionWebhookService.ports | toYaml | nindent 2 }}