apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-admission-webhook-cluster-role
  labels:
    app: poddefaults
    app.kubernetes.io/component: poddefaults
    kustomize.component: poddefaults
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - poddefaults
  verbs:
  - get
  - watch
  - list
  - update
  - create
  - patch
  - delete