apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-autoscaler
  labels:
    app: autoscaler
    app.kubernetes.io/component: autoscaler
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.autoscaler.type }}
  selector:
    app: autoscaler
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.autoscaler.ports | toYaml | nindent 2 }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "kubeflow.fullname" . }}-autoscaler
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - {}
  selector:
    matchLabels:
      app: autoscaler