apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-builtin-podspecable-binding
  labels:
    app.kubernetes.io/component: knative-eventing
    duck.knative.dev/podspecable: "true"
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs:
  - list
  - watch
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - watch
  - patch