apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-cert-manager-controller-certificates
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - certificates/status
  - certificaterequests
  - certificaterequests/status
  verbs:
  - update
  - patch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - certificaterequests
  - clusterissuers
  - issuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates/finalizers
  - certificaterequests/finalizers
  verbs:
  - update
- apiGroups:
  - acme.cert-manager.io
  resources:
  - orders
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-cert-manager-controller-certificates
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kubeflow.fullname" . }}-cert-manager-controller-certificates'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-cert-manager'
  namespace: '{{ .Release.Namespace }}'