apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-channel-addressable-resolver
  labels:
    app.kubernetes.io/component: knative-eventing
    duck.knative.dev/addressable: "true"
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - messaging.knative.dev
  resources:
  - channels
  - channels/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - messaging.knative.dev
  resources:
  - channels/finalizers
  verbs:
  - update