apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-channelable-manipulator
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      duck.knative.dev/channelable: "true"
rules: []