apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-cluster-local-gateway
  labels:
    app: cluster-local-gateway
    install.operator.istio.io/owning-resource: unknown
    istio: cluster-local-gateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.clusterLocalGateway.type }}
  selector:
    app: cluster-local-gateway
    istio: cluster-local-gateway
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.clusterLocalGateway.ports | toYaml | nindent 2 }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kubeflow.fullname" . }}-cluster-local-gateway
  labels:
    app: cluster-local-gateway
    install.operator.istio.io/owning-resource: unknown
    istio: cluster-local-gateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    release: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cluster-local-gateway
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "kubeflow.fullname" . }}-cluster-local-gateway
  labels:
    release: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  selector:
    app: cluster-local-gateway
    istio: cluster-local-gateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "kubeflow.fullname" . }}-cluster-local-gateway
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - {}
  selector:
    matchLabels:
      app: cluster-local-gateway
      istio: cluster-local-gateway