apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-config-deployment
  labels:
    app.kubernetes.io/component: controller
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: 410041a0
data:
  _example: {{ .Values.configDeployment.Example | toYaml | indent 1 }}
  progressDeadline: {{ .Values.configDeployment.progressDeadline | quote }}
  queue-sidecar-image: {{ .Values.configDeployment.queueSidecarImage | quote }}