apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-config-br-defaults
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  default-br-config: {{ .Values.configBrDefaults.defaultBrConfig | toYaml | indent
    1 }}