apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-config-br-default-channel
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  channel-template-spec: {{ .Values.configBrDefaultChannel.channelTemplateSpec |
    toYaml | indent 1 }}