apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-config-sugar
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: 62dfac6f
data:
  _example: {{ .Values.configSugar.Example | toYaml | indent 1 }}