apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-config-network
  labels:
    app.kubernetes.io/component: networking
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: 73d96d1b
data:
  _example: {{ .Values.configNetwork.Example | toYaml | indent 1 }}