apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-default-install-config-9h2h2b6hbk
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  profile-name: {{ .Values.defaultInstallConfig9H2H2B6Hbk.profileName | quote }}
  user: {{ .Values.defaultInstallConfig9H2H2B6Hbk.user | quote }}