apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-default-ch-webhook
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  default-ch-config: {{ .Values.defaultChWebhook.defaultChConfig | toYaml | indent
    1 }}