apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-dex
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - dex.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-dex
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kubeflow.fullname" . }}-dex'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-dex'
  namespace: '{{ .Release.Namespace }}'