apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeflow.fullname" . }}-domainmapping-webhook-certs
  labels:
    app.kubernetes.io/component: domain-mapping
  {{- include "kubeflow.labels" . | nindent 4 }}