apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-domainmapping-webhook
  labels:
    app.kubernetes.io/component: domain-mapping
    role: domainmapping-webhook
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.domainmappingWebhook.type }}
  selector:
    app: domainmapping-webhook
    role: domainmapping-webhook
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.domainmappingWebhook.ports | toYaml | nindent 2 }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "kubeflow.fullname" . }}-domainmapping-webhook
  labels:
    app.kubernetes.io/component: net-istio
    networking.knative.dev/ingress-provider: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  portLevelMtls:
    "8443":
      mode: PERMISSIVE
  selector:
    matchLabels:
      app: domainmapping-webhook