apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-eventing-broker-ingress
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch