apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "kubeflow.fullname" . }}-istio-webhook
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - {}
  selector:
    matchLabels:
      app: net-istio-webhook