apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-jupyter-web-app-config-7tkbmh828d
  labels:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  spawner_ui_config.yaml: {{ .Values.jupyterWebAppConfig7Tkbmh828D.spawnerUiConfigYaml
    | toYaml | indent 1 }}