apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "kubeflow.fullname" . }}-jupyter-web-app-jupyter-web-app
  labels:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /jupyter
    match:
    - uri:
        prefix: /jupyter/
    rewrite:
      uri: /
    route:
    - destination:
        host: jupyter-web-app-service.kubeflow.svc.cluster.local
        port:
          number: 80