apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-katib-config
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  katib-config.yaml: {{ .Values.katibConfig.katibConfigYaml | toYaml | indent 1 }}