apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kubeflow.fullname" . }}-kfp-cache-selfsigned-issuer
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  selfSigned: {}