apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-knative-flows-namespaced-admin
  labels:
    app.kubernetes.io/component: knative-eventing
    kustomize.component: knative
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: "true"
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - flows.knative.dev
  resources:
  - '*'
  verbs:
  - '*'