apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-knative-serving-controller-addressable-resolver
  labels:
    app.kubernetes.io/component: controller
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kubeflow.fullname" . }}-knative-serving-aggregated-addressable-resolver'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-controller'
  namespace: '{{ .Release.Namespace }}'