apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-kserve-models-web-app-config
  labels:
    app: kserve
    app.kubernetes.io/component: kserve-models-web-app
    kustomize.component: kserve-models-web-app
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  APP_PREFIX: {{ .Values.kserveModelsWebAppConfig.appPrefix | quote }}
  USERID_HEADER: {{ .Values.kserveModelsWebAppConfig.useridHeader | quote }}