apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-kserve-controller-manager-metrics-service
  labels:
    app: kserve
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: "1.0"
  {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.kserveControllerManagerMetricsService.type }}
  selector:
    app: kserve
    app.kubernetes.io/name: kserve
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: "1.0"
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.kserveControllerManagerMetricsService.ports | toYaml | nindent 2 }}