apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "kubeflow.fullname" . }}-kubeflow-self-signing-issuer
  labels:
    app.kubernetes.io/component: cert-manager
    kustomize.component: cert-manager
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  selfSigned: {}