apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-kubeflow-view
  labels:
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
  {{- include "kubeflow.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: "true"
rules: []