apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-kubeflow-pipelines-profile-controller-code-hdk828hd6c
  labels:
    app: kubeflow-pipelines-profile-controller
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  sync.py: {{ .Values.kubeflowPipelinesProfileControllerCodeHdk828Hd6C.syncPy | toYaml
    | indent 1 }}