apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-metadata-grpc-configmap
  labels:
    application-crd-id: kubeflow-pipelines
    component: metadata-grpc-server
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  METADATA_GRPC_SERVICE_HOST: {{ .Values.metadataGrpcConfigmap.metadataGrpcServiceHost
    | quote }}
  METADATA_GRPC_SERVICE_PORT: {{ .Values.metadataGrpcConfigmap.metadataGrpcServicePort
    | quote }}