apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-metadata-envoy-service
  labels:
    app: metadata-envoy
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metadataEnvoyService.type }}
  selector:
    application-crd-id: kubeflow-pipelines
    component: metadata-envoy
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metadataEnvoyService.ports | toYaml | nindent 2 }}