apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline-scheduledworkflow-binding
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "kubeflow.fullname" . }}-ml-pipeline-scheduledworkflow-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-ml-pipeline-scheduledworkflow'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline-scheduledworkflow-binding
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kubeflow.fullname" . }}-ml-pipeline-scheduledworkflow-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-ml-pipeline-scheduledworkflow'
  namespace: '{{ .Release.Namespace }}'