apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline-ui
  labels:
    app: ml-pipeline-ui
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - kubeflow.org
  resources:
  - viewers
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline-ui
  labels:
    app: ml-pipeline-ui
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - kubeflow.org
  resources:
  - viewers
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline-ui
  labels:
    app: ml-pipeline-ui
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "kubeflow.fullname" . }}-ml-pipeline-ui'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-ml-pipeline-ui'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline-ui
  labels:
    app: ml-pipeline-ui
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kubeflow.fullname" . }}-ml-pipeline-ui'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-ml-pipeline-ui'
  namespace: '{{ .Release.Namespace }}'