apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline-persistenceagent-role
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - scheduledworkflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - scheduledworkflows
  - workflows
  verbs:
  - report
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - runs
  verbs:
  - reportMetrics
  - readArtifact
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-ml-pipeline-persistenceagent-role
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - scheduledworkflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - scheduledworkflows
  - workflows
  verbs:
  - report
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - runs
  verbs:
  - reportMetrics
  - readArtifact