apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubeflow.fullname" . }}-mysql-pv-claim
  labels:
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.mysqlPvClaim.storageRequest | quote }}