apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-namespace-labels-data-4df5t8mdgf
  labels:
    kustomize.component: profiles
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  namespace-labels.yaml: {{ .Values.namespaceLabelsData4Df5T8Mdgf.namespaceLabelsYaml
    | toYaml | indent 1 }}