apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeflow.fullname" . }}-net-istio-webhook-certs
  labels:
    app.kubernetes.io/component: net-istio
    networking.knative.dev/ingress-provider: istio
  {{- include "kubeflow.labels" . | nindent 4 }}