apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-oidc-authservice-parameters
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  AFTER_LOGOUT_URL: {{ .Values.oidcAuthserviceParameters.afterLogoutUrl | quote }}
  AUTHSERVICE_URL_PREFIX: {{ .Values.oidcAuthserviceParameters.authserviceUrlPrefix
    | quote }}
  OIDC_AUTH_URL: {{ .Values.oidcAuthserviceParameters.oidcAuthUrl | quote }}
  OIDC_PROVIDER: {{ .Values.oidcAuthserviceParameters.oidcProvider | quote }}
  OIDC_SCOPES: {{ .Values.oidcAuthserviceParameters.oidcScopes | quote }}
  PORT: {{ .Values.oidcAuthserviceParameters.port | quote }}
  SKIP_AUTH_URLS: {{ .Values.oidcAuthserviceParameters.skipAuthUrls | quote }}
  STORE_PATH: {{ .Values.oidcAuthserviceParameters.storePath | quote }}
  USERID_CLAIM: {{ .Values.oidcAuthserviceParameters.useridClaim | quote }}
  USERID_HEADER: {{ .Values.oidcAuthserviceParameters.useridHeader | quote }}
  USERID_PREFIX: {{ .Values.oidcAuthserviceParameters.useridPrefix | quote }}