apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-pipeline-runner-binding
  labels:
    app.kubernetes.io/component: ml-pipeline
    application-crd-id: kubeflow-pipelines
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "kubeflow.fullname" . }}-pipeline-runner'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-pipeline-runner'
  namespace: '{{ .Release.Namespace }}'