apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-pvcviewer-webhook-service
  labels:
    app: pvcviewer
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/part-of: pvc-viewer
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pvcviewerWebhookService.type }}
  selector:
    app: pvcviewer
    control-plane: controller-manager
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.pvcviewerWebhookService.ports | toYaml | nindent 2 }}