apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-pvcviewer-controller-manager-metrics-service
  labels:
    app: pvcviewer
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/part-of: pvc-viewer
    control-plane: controller-manager
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pvcviewerControllerManagerMetricsService.type }}
  selector:
    app: pvcviewer
    control-plane: controller-manager
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.pvcviewerControllerManagerMetricsService.ports | toYaml | nindent 2 }}