apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kubeflow.fullname" . }}-pvcviewer-serving-cert
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "kubeflow.fullname" . }}-pvcviewer-webhook-service.kubeflow.svc'
  - '{{ include "kubeflow.fullname" . }}-pvcviewer-webhook-service.kubeflow.svc.{{ .Values.kubernetesClusterDomain
    }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "kubeflow.fullname" . }}-pvcviewer-selfsigned-issuer'
  secretName: webhook-server-cert