apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-pvcviewer-manager-rolebinding
  labels:
    app: pvcviewer
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/part-of: pvc-viewer
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kubeflow.fullname" . }}-pvcviewer-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-pvcviewer-controller-manager'
  namespace: '{{ .Release.Namespace }}'