apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-service-addressable-resolver
  labels:
    app.kubernetes.io/component: knative-eventing
    duck.knative.dev/addressable: "true"
    kustomize.component: knative
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch