apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.fullname" . }}-tensorboard-controller-config-b98cb9gk9k
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
data:
  ISTIO_GATEWAY: {{ .Values.tensorboardControllerConfigB98Cb9Gk9K.istioGateway |
    quote }}
  RWO_PVC_SCHEDULING: {{ .Values.tensorboardControllerConfigB98Cb9Gk9K.rwoPvcScheduling
    | quote }}
  TENSORBOARD_IMAGE: {{ .Values.tensorboardControllerConfigB98Cb9Gk9K.tensorboardImage
    | quote }}