apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeflow.fullname" . }}-volumes-web-app-cluster-role-binding
  labels:
    app: volumes-web-app
    kustomize.component: volumes-web-app
  {{- include "kubeflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kubeflow.fullname" . }}-volumes-web-app-cluster-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kubeflow.fullname" . }}-volumes-web-app-service-account'
  namespace: '{{ .Release.Namespace }}'