apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.fullname" . }}-volumes-web-app-kubeflow-volume-ui-edit
  labels:
    app: volumes-web-app
    kustomize.component: volumes-web-app
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
  {{- include "kubeflow.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - kubeflow.org
  resources:
  - pvcviewers
  verbs:
  - get
  - list
  - create
  - delete