apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.fullname" . }}-webhook
  labels:
    app.kubernetes.io/component: webhook
    role: webhook
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.type }}
  selector:
    app: webhook
    role: webhook
  {{- include "kubeflow.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhook.ports | toYaml | nindent 2 }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kubeflow.fullname" . }}-webhook
  labels:
    app.kubernetes.io/component: webhook
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 100
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webhook
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "kubeflow.fullname" . }}-webhook
  labels:
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - {}
  selector:
    matchLabels:
      role: webhook
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "kubeflow.fullname" . }}-webhook
  labels:
    app.kubernetes.io/component: net-istio
    networking.knative.dev/ingress-provider: istio
  {{- include "kubeflow.labels" . | nindent 4 }}
spec:
  portLevelMtls:
    "8443":
      mode: PERMISSIVE
  selector:
    matchLabels:
      app: webhook